<a href="https://colab.research.google.com/github/aparna-2001/matrix-properties-calculator/blob/main/Mini_project1_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Data Matrix calculator**

- upload the data file

- convert it to matrix (if needed first table to then matrix)

-find the order

-if order m = n

- find the determinant - inference

- find the inverse - inference

- find the eigen values and eigen vector - inference

- find the rank




**CODE VERSION 1**

In [39]:
#input of data

import numpy as np
import pandas as pd
import csv


#file input
data = pd.read_csv("data.csv") #replace it with your file name
print(data)

#checking the order
data_table = pd.DataFrame(data)
print(f"The data in table:{data_table}")

#conversion to matrix
def conversion_to_matrix(data):
    matrix_array = np.array(data)
    print(f"Converted matrix: {matrix_array}")
    return matrix_array

# Call the conversion function and store the result
matrix_input = conversion_to_matrix(data)


#finding the rank
def matrix_rank(matrix_input):
  matrix_rank = np.linalg.matrix_rank(matrix_input)
  print(f"Rank of matrix: {matrix_rank}")
  return matrix_rank

matrix_rank(matrix_input)



#finding the determinant
def det_matrix(matrix_input):
    try:
      matrix_1_det = np.linalg.det(matrix_input)
      print(f"Determinant of the matrix: {matrix_1_det}")
    except:
      print("This is a non square matrix")

det_matrix(matrix_input)

#finding the inverse
def inverse_matrix(matrix_input):
  try:
    matrix_inverse = np.linalg.inv(matrix_input)
    print(f"Inverse of the matrix: {matrix_inverse}")
  except:
    print("Inverse doesn't exist: The matrix is singular or the matrix is a non square matrix")

inverse_matrix(matrix_input)


#finding the Eigen values and Eigen vector
def eigen_matrix(matrix_input):
  try:
    Eigen_values,Eigen_matrix = np.linalg.eig(matrix_input)
    print(f"Eigen values of the matrix: {Eigen_values}")
    print(f"Eigen vectors of the matrix: {Eigen_matrix}")
  except:
    print("The matrix is not a square matrix")

eigen_matrix(matrix_input)


   x  y  z
0  1  2  3
1  4  5  6
2  7  8  9
The data in table:   x  y  z
0  1  2  3
1  4  5  6
2  7  8  9
Converted matrix: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Rank of matrix: 2
Determinant of the matrix: 0.0
Inverse doesn't exist: The matrix is singular or the matrix is a non square matrix
Eigen values of the matrix: [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
Eigen vectors of the matrix: [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


**CODE VERSION 2**

Below is a another version of code

In [38]:
#input of data

import numpy as np
import pandas as pd
import csv


#file input
data = pd.read_csv("data.csv") #replace with your file name
print(data)

#To table
data_table = pd.DataFrame(data)
print(f"The data in table:{data_table}")

#conversion to matrix
def conversion_to_matrix(data):
    matrix_array = np.array(data)
    print(f"Converted matrix: {matrix_array}")
    return matrix_array

# Call the conversion function and store the result
matrix_input = conversion_to_matrix(data)


#finding the rank
def matrix_rank(matrix_input):
  matrix_rank = np.linalg.matrix_rank(matrix_input)
  print(f"Rank of matrix: {matrix_rank}")
  return matrix_rank

matrix_rank(matrix_input)


if matrix_input.shape[0]==matrix_input.shape[1]:

      Eigen_values,Eigen_matrix = np.linalg.eig(matrix_input) #Eigen values
      print(f"Eigen values of the matrix: {Eigen_values}")
      print(f"Eigen vectors of the matrix: {Eigen_matrix}")

      matrix_1_det = np.linalg.det(matrix_input) #determinant
      print(f"Determinant of the matrix: {matrix_1_det}")

      if matrix_1_det != 0:
         matrix_inverse = np.linalg.inv(matrix_input) #inverse
         print(f"Inverse of the matrix: {matrix_inverse}")
      else:
        print("Inverse doesn't exist: The matrix is singular or the matrix is a non square matrix")

else:
  print("Matrix is not square, cannot calculate determinant, inverse, or eigen values/vectors.")


   x  y  z
0  1  2  3
1  4  5  6
2  7  8  9
The data in table:   x  y  z
0  1  2  3
1  4  5  6
2  7  8  9
Converted matrix: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Rank of matrix: 2
Eigen values of the matrix: [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
Eigen vectors of the matrix: [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
Determinant of the matrix: 0.0
Inverse doesn't exist: The matrix is singular or the matrix is a non square matrix
